areaazul/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls') ),
    path('cliente/', include('cliente.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.entrar, name='login'),
    path('sair/', views.sair, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('perguntas_frequentes/', views.perguntas_frequentes, name='perguntas_frequentes'),
    path('sobre_nos/', views.sobre_nos, name='sobre_nos'),
    path('contato/', views.contato, name='contato'),

    path('esqueci_senha/', auth_views.PasswordResetView.as_view(template_name='home/esqueci_senha.html'), name='reset_password'),
    path('mudar_senha_solicitação/', auth_views.PasswordResetDoneView.as_view(template_name='home/solicitação_nova_senha.html'), name='password_reset_done'),
    path('mudar_senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='home/definição_nova_senha.html'), name='password_reset_confirm'),
    path('mudar_senha_completo/', auth_views.PasswordResetCompleteView.as_view(template_name='home/senha_alterada_sucesso.html'), name='password_reset_complete')
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Address(models.Model):
    zip_code = models.CharField(max_length=9, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    district = models.CharField(max_length=100, null=True, blank=True)
    street_name = models.CharField(max_length=100, null=True, blank=True)
    house_number = models.CharField(max_length=6, null=True, blank=True)
    complement = models.CharField(max_length=200, null=True, blank=True)

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    phone2 = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100)
    credits = models.FloatField(default=0)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    address = models.ForeignKey(Address, null=True, blank=True, on_delete=models.SET_NULL)
    profile_pic = models.ImageField(default='generic_profile.png', null=True, blank=True)

    def __str__(self):
        return self.name

class Vehicle(models.Model):
    VEHICLES_TYPE = (
        ('C', 'Car'),
        ('M', 'Moto'),
        ('O', 'Other'),
    )
    license_plate = models.CharField(max_length=7)
    day_parked = models.DateField(null=True, blank=True, auto_now=True)
    entry_time = models.TimeField(null=True, blank=True)
    expiration_time = models.TimeField(null=True, blank=True)
    timer = models.IntegerField(null=True, blank=True, default=0)
    vehicle_type = models.CharField(max_length=1, choices=VEHICLES_TYPE)
    owners = models.ManyToManyField(Client)

    def __str__(self):
        return self.license_plate

class Operation(models.Model):
    OPERATION_TYPE = (
        ('Estacionar', 'Estacionar'),
        ('Compra de Créditos', 'Compra de Créditos'),
    )
    PAYMENT_METHOD = (
        ('Crédito', 'Crédito'),
        ('Débito', 'Débito'),
        ('Pix', 'Pix'),
    )
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    operation_type = models.CharField(max_length=70, choices=OPERATION_TYPE)
    payment_method = models.CharField(max_length=70, choices=PAYMENT_METHOD, null=True, blank=True)
    vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete=models.SET_NULL)
    value = models.FloatField()
    balance = models.FloatField()

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'phone1', 'phone2', 'profile_pic']


class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = '__all__'


class CreateUser(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password1', 'password2']

home/views.py
from home.decorators import unauthenticated_user
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib import messages

from .models import *
from .forms import *
from .filters import *
from .decorators import *

@unauthenticated_user
def entrar(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
    
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.add_message(request, messages.ERROR, 'Login ou senha incorretos.')

    context = {}
    return render(request, 'home/login.html', context)


def sair(request):
    logout(request)
    return redirect('login')


@unauthenticated_user
def esqueci_senha(request):
    return render(request, 'home/esqueci_senha.html')


@unauthenticated_user
def cadastro(request):
    form = CreateUser()
    if request.method == 'POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            user = form.save()
            name = form.cleaned_data.get('first_name')
            email = form.cleaned_data.get('email')

            group = Group.objects.get(name='Client')
            user.groups.add(group)
            
            emptyAddress = Address.objects.create(
                zip_code='', state='', city='', district='', street_name='', house_number='', complement=''
            )

            Client.objects.create(
                user=user, name=name, email=email, address=emptyAddress
            )

            messages.add_message(request, messages.SUCCESS, 'Parabéns, ' + name + '. Sua conta foi cadastrada com sucesso!')
            return redirect('login')

    context = {'form': form}
    return render(request, 'home/cadastro.html', context)


@unauthenticated_user
def perguntas_frequentes(request):
    return render(request, 'home/perguntas_frequentes.html')


@unauthenticated_user
def sobre_nos(request):
    return render(request, 'home/sobre_nos.html')


@unauthenticated_user
def contato(request):
    return render(request, 'home/contato.html')

home/templates/home/base_home.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'imagens/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'imagens/favicon-16x16.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@600&display=swap" rel="stylesheet">
    <title>Área Azul - Blumenau</title>
</head>

<body>
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src='{% static "js/jquery.mask.js" %}'></script>
    <script src="{% static 'js/home.js' %}"></script>
</body>

</html>

home/templates/home/cadastro.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class='main-cadastro'>
    <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
    <h2>Cadastre-se</h2>
    <form class="div-register" method="POST" action="">
        {% csrf_token %}
        <div class="div_home_input">
            {{form.username}}
            <label for="Login" class="home_input_label" autocomplete="off">CPF</label>
        </div>

        <div class="div_home_input">
            {{form.first_name}}
            <label for="nome" class="home_input_label">Nome</label>
        </div>

        <div class="div_home_input">
            {{form.email}}
            <label for="e-mail" class="home_input_label">E-mail</label>
        </div>

        <div class="div_home_input">
            {{form.password1}}
            <label for="password1" class="home_input_label">Senha</label>
        </div>
        
        <div class="div_home_input">
            {{form.password2}}
            <label for="password2" class="home_input_label">Confirmar Senha</label>
        </div>

        {{form.errors}}

        <button type="submit" class="btn btn-cadastrar" disabled>Cadastrar</button>   
    </form>
</main>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src='{% static "js/jquery.mask.js" %}'></script>

<script>
    var form_fields = document.getElementsByTagName("input");

    for (var field in form_fields) {
      form_fields[field].className += "home_input register_input";
      form_fields[field].onkeyup = function() {
          verifyInputs()
      }
    }


    $('#id_username').mask('000.000.000-00')

    $('#id_username').attr("autocomplete", "off");

    function verifyInputs() {
        if (($('#id_username').val().length == 14) && 
            ($('#id_first_name').val() != '') &&
            ($('#id_email').val() != '') &&
            ($('#id_password1').val() != '') &&
            ($('#id_password2').val() != '')) 
                document.getElementsByClassName('btn')[0].disabled = false
        else {
            document.getElementsByClassName('btn')[0].disabled = true
        }
    }

</script>

{% endblock %}

home/templates/home/contato.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class="main-cadastro contato">
    <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
    <h2>Contato</h2>
    <form>
        <input type="text" name="Nome" placeholder="NOME" required id="contato-nome" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()">
        <input type="text" name="E-mail" placeholder="E-MAIL" required id="contato-email" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()">
        <input type="text" name="Telefone" placeholder="TELEFONE" required id="contato-telefone" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()">
        <input type="text" name="Cidade" placeholder="CIDADE" required id="contato-cidade" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()">
        <input type="text" name="Assunto" placeholder="ASSUNTO" required id="contato-assunto" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()">
        <textarea name="subject" placeholder="MENSAGEM" id="contato-mensagem" onfocus="innerBoxShadow(this)" onblur="removeInnerBox(this)" onkeyup="verifyInputs()"></textarea>
        <button type="button" class="btn btn-cadastrar" disabled>Enviar</button>
     </form>
</main>

<script>
    let nome = document.getElementById('contato-nome')
    let email = document.getElementById('contato-email')
    let telefone = document.getElementById('contato-telefone')
    let cidade = document.getElementById('contato-cidade')
    let assunto = document.getElementById('contato-assunto')
    let mensagem = document.getElementById('contato-mensagem')


    function innerBoxShadow(input) {
        input.classList.add('inner-box-shadow')
    }


    function removeInnerBox(input) {
        input.classList.remove('inner-box-shadow')
    }


    var disabled = true


    function verifyInputs() {
        if (($('#contato-nome').val() != '') && 
            ($('#contato-email').val() != '') &&
            ($('#contato-telefone').val() != '') &&
            ($('#contato-cidade').val() != '') &&
            ($('#contato-assunto').val() != '') &&
            ($('#contato-mensagem').val() != '')) 
                document.getElementsByClassName('btn')[0].disabled = false
        else {
            document.getElementsByClassName('btn')[0].disabled = true
        }
    }
    
</script>
{% endblock %}

home/templates/home/definição_nova_senha.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<form class="esqueci_senha_form" action="" id="form" method="POST">
    {% csrf_token %}
    <img src="{% static 'imagens/Logo-A-provisorio.png' %}" alt="Logo Área Azul" class="logo" onclick="location.href='{% url 'login' %}'">
    <h2 id="nova-senha-title">Altere sua Senha</h2>
    <div class="div_home_input">
        {{form.new_password1}}
        <label for="log_input" class="home_input_label">Nova Senha</label>  
    </div>
    <div class="div_home_input">
        {{form.new_password2}}
        <label for="log_input" class="home_input_label">Confirmação da Senha</label>
    </div>
    <button type="submit" class="btn" id="btn-nova-senha">Enviar</button>
</form>

<script>
    var form_fields = document.getElementsByTagName("input");

    for (var field in form_fields) {
        form_fields[field].className += "home_input new_password_input";
    }
</script>

{% endblock %}

home/templates/home/esqueci_senha.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<form class="esqueci_senha_form" action="" id="form" method="POST">
    {% csrf_token %}
    <img src="{% static 'imagens/Logo-A-provisorio.png' %}" alt="Logo Área Azul" class="logo" onclick="location.href='{% url 'login' %}'">
    <h2>Esqueci minha senha</h2>
    <div class="div_home_input">
        {{form.email}}
        <label for="log_input" class="home_input_label">E-mail</label>
    </div>
    <button type="submit" class="btn" disabled>Enviar</button>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/

    $('#id_email').addClass("home_input")
    $('#id_email').keyup(function() {
        let validEmail = $("#id_email").val()
        if (!emailReg.test(validEmail) == false) document.getElementsByClassName('btn')[0].disabled = false
        else {
            document.getElementsByClassName('btn')[0].disabled = true
        }
    });
 
</script>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

<div class="div_upper">
    <div class="div_upper_logo">
        <img src="{% static 'imagens/Logo-B-provisorio.png'%}" alt="areaazul-logo" class="logo">
    </div>

    <div class="div_upper_nav">
        <a href="">Home</a>
        <a href="{% url 'perguntas_frequentes' %}">Perguntas Frequentes</a>
        <a href="{% url 'sobre_nos' %}">Sobre Nós</a>
        <a href="{% url 'contato' %}">Contato</a>
    </div>
</div>

<div class="div_body">
    <div class="div_body_text">
        <h1>Desde 1984</h1>
        <h2>Agora mais prático e rápido para estacionar no centro de Blumenau.</h2>
    </div>

    <div class="div_login_box">
        <h1>Faça seu login</h1>

        <form action="" method="POST">
            {% csrf_token %}

            <div class="div_home_input">
                <input type="text" class="home_input" id="username" name="username" onkeyup="verifyLogin()" autocomplete="off" maxlength="14" required>
                <label for="username" class="home_input_label">CPF</label>
            </div>
            <div class="div_home_input input_space">
                <input type="password" class="home_input" id="password" name="password" onkeyup="verifyLogin()" required>
                <label for="password" class="home_input_label">Senha</label>
            </div>
        
            <a href="{% url 'reset_password' %}">Esqueci minha senha</a>

            {% if messages %}
                {% for message in messages %}
                
                    <div class="home_messages {{message.tags}}">
                        <p>{{message}}</p><button type="button" class="btn-close" onclick="deletarMensagem(this)">&times;</button>
                    </div>
        
                {% endfor %}
            {% endif %}

            <button class="btn btn-login" type="submit" disabled>Continuar</button>
            <a href="{% url 'cadastro' %}">Ainda não sou cadastrado</a>
        </form>
    </div>
</div>

{% endblock %}

home/templates/home/perguntas_frequentes.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class="main-cadastro perguntas-frequentes">
  <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
  <h2>Perguntas Frequentes</h2>
  <button class="accordion">Como funciona o sistema ‘Área Azul’?</button>
  <div class="panel">
    <p>O usuário, através de um cadastro simples realizado no sistema, deverá criar uma conta online, onde poderá comprar créditos eletrônicos e adicionar tempo e valor no veículo estacionado em qualquer vaga regulamentada da Área Azul, demarcada por sinalização (placa).</p>
  </div>

  <button class="accordion">O que é a conta online?</button>
  <div class="panel">
    <p>É uma conta pessoal que será criada pelo usuário em nosso site, onde ficarão registrados todo o histórico de ações da Área Azul e créditos adquiridos exclusivamente para a mesma. Esta conta não tem qualquer relação com sua conta bancária.</p>
  </div>

  <button class="accordion">Como funciona a fiscalização através do sistema?</button>
  <div class="panel">
    <p>O sistema de estacionamento regulamentado, indicativo nas respectivas placas de regulamentação, obriga ao usuário utilizar o cartão de estacionamento ou o sistema automatizado para fiscalização dos monitores da Área Azul. O usuário deve adicionar o tempo desejado na placa do veículo estacionado e realizar o pagamento. Caso o usuário não o faça, o monitor aplicará uma Notificação de Regularização (NR).</p>
  </div>

  <button class="accordion">Qual o valor e prazo de pagamento da NR?</button>
  <div class="panel">
    <p>Quando o usuário NÃO utiliza o cartão ou o sistema automatizado de estacionamento pagará a NR, cujos valores das tarifas diferem quanto ao tipo de veículo como segue:</p>
    <p><strong>Motos:</strong>R$ 5,00 por hora estacionada</p>
    <p><strong>Demais Veículos:</strong>R$ 10,00 por hora estacionada</p>
    <br>
    <p>O usuário dispõe de 15 dias corridos após a emissão para efetuar o pagamento da NR. Caso não seja efetuado o pagamento haverá geração de multa ao infrator. Desde o dia 1º de janeiro de 2016 a infração de estacionamento irregular é considerada grave pelo Código de Trânsito Brasileiro, conforme a lei nº 13.146/2015. O valor da multa é de R$ 195,23 e gera perda de 5 (cincos) pontos na carteira de habilitação.</p>
  </div>

  <button class="accordion">Qual é o horário de cobrança da Área Azul?</button>
  <div class="panel">
    <p>O horário de cobrança da Área Azul vai das 8h às 18h de segunda a sexta-feira, e das 8h às 12h aos sábados, conforme as placas indicativas.</p>
  </div>
</main>

{% endblock %}

home/templates/home/senha_alterada_sucesso.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class="main-cadastro trocar-senha">
    <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
    <div>
        <p class='msg-senha'>• Sua senha foi redefinida com sucesso.</p>
    </div>
    <a href="{% url 'login' %}"><button class='btn redirect-login'>Logar</button></a>
</main>

{% endblock %}

home/templates/home/sobre_nos.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class="main-cadastro sobre-nos">
  <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
  <h2>Sobre Nós</h2>
  <div>
    <h3>Estacionamento Rotativo Regularizado</h3>
    <p>A Área Azul foi implantada no município de Blumenau no dia 3 de setembro de 1984, abrangendo em seu início 21 ruas totalizando 385 vagas.</p>
  </div>
  <div>
    <h3>Motivações para a Implantação</h3>
    <p>• Localização geográfica da área central entre o rio Itajaí e elevações, dispondo de apenas três vias principais de escoamento de tráfego;</p>
    <p>• Elevada média de veículos por habitante;</p>
    <p>• Concentração comercial, foco gerador de tráfego;</p>
    <p>• Uso constante do estacionamento de longa duração nas áreas mais congestionadas;</p>
    <p>• Demanda por espaço superior à oferta de vagas.</p>
  </div>
  <div>
    <h3>Objetivos da Área Azul</h3>
    <p>• Maximizar, igualar e democratizar a probabilidade de estacionamento para veículos cujos ocupantes se dirigem às compras, aos negócios, entre outros;</p>
    <p>• Disciplinar fluxo de tráfego, aumento da produtividade do sistema viário e economia de combustível;</p>
    <p>• Diminuir a incidência de veículos estacionados de forma irregular;</p>
    <p>• Estimular e promover a atividade comercial.</p>
  </div>
</main>

{% endblock %}

home/templates/home/solicitação_nova_senha.html
{% extends 'home/base_home.html' %}
{% load static %}

{% block content %}

{% include 'partials/_sidenav.html' %}

<main class="main-cadastro trocar-senha">
    <img src="{% static 'imagens/Logo-A-provisorio.png'%}" height="75px" alt="Logo Área Azul" onclick="location.href='{% url 'login' %}'">
    <div>
        <p class='msg-senha'>• Instruções para a redefinição de senha foram enviadas para o e-mail informado. Você deve recebê-lo em breve.</p>
        <p class='msg-senha'>• Caso não tenha recebido nada, verifique sua caixa de spam e se o e-mail foi digitado corretamente.</p>
    </div>
</main>

{% endblock %}