areaazul/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls') ),
    path('cliente/', include('cliente.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cliente/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:pk>/estacionar/", views.estacionar, name="estacionar"),
    path("<str:pk>/extrato/", views.extrato, name="extrato"),
    path("<str:pk>/creditos/", views.creditos, name="creditos"),
    path("<str:pk>/veiculos/", views.veiculos, name="veiculos"),
    path("<str:pk_client>/veiculos/excluir/<str:pk_vehicle>/", views.excluirVeiculo, name="excluirVeiculo"),
    path("<str:pk>/dados/", views.dados, name="dados"),
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.entrar, name='login'),
    path('sair/', views.sair, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('perguntas_frequentes/', views.perguntas_frequentes, name='perguntas_frequentes'),
    path('sobre_nos/', views.sobre_nos, name='sobre_nos'),
    path('contato/', views.contato, name='contato'),

    path('esqueci_senha/', auth_views.PasswordResetView.as_view(template_name='home/esqueci_senha.html'), name='reset_password'),
    path('mudar_senha_solicitação/', auth_views.PasswordResetDoneView.as_view(template_name='home/solicitação_nova_senha.html'), name='password_reset_done'),
    path('mudar_senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='home/definição_nova_senha.html'), name='password_reset_confirm'),
    path('mudar_senha_completo/', auth_views.PasswordResetCompleteView.as_view(template_name='home/senha_alterada_sucesso.html'), name='password_reset_complete')
]

cliente/models.py
from django.db import models

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Address(models.Model):
    zip_code = models.CharField(max_length=9, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    district = models.CharField(max_length=100, null=True, blank=True)
    street_name = models.CharField(max_length=100, null=True, blank=True)
    house_number = models.CharField(max_length=6, null=True, blank=True)
    complement = models.CharField(max_length=200, null=True, blank=True)

class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    phone2 = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100)
    credits = models.FloatField(default=0)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    address = models.ForeignKey(Address, null=True, blank=True, on_delete=models.SET_NULL)
    profile_pic = models.ImageField(default='generic_profile.png', null=True, blank=True)

    def __str__(self):
        return self.name

class Vehicle(models.Model):
    VEHICLES_TYPE = (
        ('C', 'Car'),
        ('M', 'Moto'),
        ('O', 'Other'),
    )
    license_plate = models.CharField(max_length=7)
    day_parked = models.DateField(null=True, blank=True, auto_now=True)
    entry_time = models.TimeField(null=True, blank=True)
    expiration_time = models.TimeField(null=True, blank=True)
    timer = models.IntegerField(null=True, blank=True, default=0)
    vehicle_type = models.CharField(max_length=1, choices=VEHICLES_TYPE)
    owners = models.ManyToManyField(Client)

    def __str__(self):
        return self.license_plate

class Operation(models.Model):
    OPERATION_TYPE = (
        ('Estacionar', 'Estacionar'),
        ('Compra de Créditos', 'Compra de Créditos'),
    )
    PAYMENT_METHOD = (
        ('Crédito', 'Crédito'),
        ('Débito', 'Débito'),
        ('Pix', 'Pix'),
    )
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    operation_type = models.CharField(max_length=70, choices=OPERATION_TYPE)
    payment_method = models.CharField(max_length=70, choices=PAYMENT_METHOD, null=True, blank=True)
    vehicle = models.ForeignKey(Vehicle, null=True, blank=True, on_delete=models.SET_NULL)
    value = models.FloatField()
    balance = models.FloatField()

cliente/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from home.models import Address, Client, Vehicle, Operation
from home.forms import AddressForm, ClientForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from home.filters import *
from django.core.paginator import Paginator


@login_required(login_url='login')
def index(request):
    return render(request, "cliente/index.html", {})


@login_required(login_url='login')
def estacionar(request, pk):
    client = Client.objects.get(pk=pk)
    cars = client.vehicle_set.filter(vehicle_type='C')
    motos = client.vehicle_set.filter(vehicle_type='M')
    others = client.vehicle_set.filter(vehicle_type='O')
    vehicles = Vehicle.objects.filter(owners__id=pk)

    if request.method == 'POST':
        plate = request.POST['license_plate']
        entry = request.POST['entry_time']
        expiration = request.POST['expiration_time']
        creditos = request.POST['value']

        for vehicle in vehicles:
            vehicle.entry_time = None
            vehicle.expiration_time = None
            vehicle.save()

        parkedVehicle = Vehicle.objects.get(license_plate=plate)
        parkedVehicle.entry_time = entry
        parkedVehicle.expiration_time = expiration
        parkedVehicle.save()

        balanco = client.credits
        newBalance = balanco - float(creditos)

        client.credits -= float(creditos)
        client.save()

        Operation.objects.create(
            client=client, operation_type="Estacionar", vehicle=parkedVehicle, value=creditos, balance=newBalance
        )

        return redirect('estacionar', client.pk)
    
    context = {'client':client, 'cars':cars, 'motos':motos, 'others':others, 'vehicles':vehicles}
    return render(request, "cliente/estacionar.html", context)


@login_required(login_url='login')
def extrato(request, pk):
    client = Client.objects.get(pk=pk)
    operations = client.operation_set.all().order_by('-date')
    
    operationFilter = OperationsFilter(request.GET, queryset=operations)
    operations = operationFilter.qs

    paginator = Paginator(operations, 8)
    page = request.GET.get('page')
    operations = paginator.get_page(page)

    context = {'client':client, 'operations':operations, 'operation_filter':operationFilter}
    return render(request, "cliente/extrato.html", context)


@login_required(login_url='login')
def creditos(request, pk):
    client = Client.objects.get(id=pk)

    if request.method == 'POST':
        creditos = request.POST['value']
        operacao = request.POST['operation']
        pagamento = request.POST['payment_method']
        balanco = client.credits
        newBalance = balanco + float(creditos)

        client.credits += float(creditos)
        client.save()

        Operation.objects.create(
            client=client, operation_type=operacao, payment_method=pagamento, value=creditos, balance=newBalance
        )

    return render(request, "cliente/adicionar_creditos.html")


@login_required(login_url='login')
def veiculos(request, pk):
    client = Client.objects.get(pk=pk)
    cars = client.vehicle_set.filter(vehicle_type='C')
    motos = client.vehicle_set.filter(vehicle_type='M')
    others = client.vehicle_set.filter(vehicle_type='O')
    vehicles = Vehicle.objects.filter(owners__id=pk)

    if request.method == 'POST':
        plate = request.POST['license_plate']
        type = request.POST['vehicle_type']

        newVehicle = Vehicle.objects.create(
            license_plate = plate, 
            vehicle_type = type
        )

        newVehicle.owners.add(client)

        return redirect('veiculos', client.pk)
    
    context = {'client':client, 'cars':cars, 'motos':motos, 'others':others, 'vehicles':vehicles}
    return render(request, "cliente/veiculos.html", context)


@login_required(login_url='login')
def excluirVeiculo(request, pk_client, pk_vehicle):
    client = Client.objects.get(id=pk_client)
    vehicle = Vehicle.objects.get(id=pk_vehicle)

    if request.method == 'POST':
        vehicle.delete()
        messages.add_message(request, messages.SUCCESS, 'Veículo excluído com sucesso!')

        return redirect('veiculos', client.pk)

    context = {'client':client, 'vehicle':vehicle}
    return render(request, "cliente/excluir.html", context)


@login_required(login_url='login')
def dados(request, pk):
    client = Client.objects.get(pk=pk)
    address = client.address

    clientForm = ClientForm(instance=client)
    addressForm = AddressForm(instance=address)

    if request.method == 'POST':
        clientForm = ClientForm(request.POST, request.FILES, instance=client)
        addressForm = AddressForm(request.POST, instance=address)
        if clientForm.is_valid() and addressForm.is_valid():
            clientForm.save()
            addressForm.save()
            messages.add_message(request, messages.SUCCESS, 'Dados atualizados com sucesso!')
        else:
            messages.add_message(request, messages.ERROR, 'Um erro ocorreu. Por favor, tente novamente.')


    context = {'client':client, 'clientForm':clientForm, 'addressForm':addressForm}
    return render(request, "cliente/dados.html", context)

cliente/templates/cliente/adicionar_creditos.html
{% extends 'cliente/base_clientes.html' %}
{% load static %}

{% block content %}
    <script>
        document.getElementById('page-title').innerHTML = 'Adicionar Créditos'
    </script>

    <div class="informations_add_credits">

        <div id="saldo_add_credits">
            <h2 class="add-creditos-title">Saldo Atual:</h2>
            <div class="informations">
                <img src="{% static 'imagens/valor.png' %}" alt="stylesheet">
                <div class="box">
                    <p>R$ <span id="saldo-atual">{{user.client.credits|floatformat:2}}</span></p>
                </div>
            </div>
        </div>

        <div id="saldo_add_credits">
            <h2 class="add-creditos-title">Valor a Adicionar:</h2>
            <div class="informations">
                <img src="{% static 'imagens/valor2.png' %}" alt="stylesheet">
                <div class="box">
                    <p class="total-creditos">R$ 0,00</p>
                </div>
            </div>
        </div>

        <div>
            <h2 class="add-creditos-title">Saldo Final:</h2>
            <div class="informations">
                <img src="{% static 'imagens/Adicionar_Creditos_Blue.png' %}" alt="stylesheet">
                <div class="box" style="border-color: var(--cor12);">
                    <p id="saldo-final" style="color: var(--cor12);"></p>
                </div>
            </div>
        </div>
        
    </div>

    <div class="add_credits">
        {% include 'partials/_add_credits.html' %}
    </div>

    <div class="payment_method_add_credits">
        {% include 'partials/_payment_method.html' %}
    </div>

    <div class="cliente_messages msg-success" id="div-msg-creditos" style="display: none;">
        <p id="msg-credito-adicionado"></p><button type="button" class="btn-close" onclick="deletarMensagem(this)">&times;</button>
    </div>

    <form id="add-credits-form">
        {% csrf_token %}
        <div class="button_confirm">
            <button type="submit" id="btn-confirm-credits" onclick="forcedReload()" disabled>Confirmar</button>
        </div>
    </form>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/adicionar_creditos.js' %}"></script>
    <script>
        // Changing the color of payment_method images.
        var imgCredit = document.getElementById('img-credit')
        var imgDebit = document.getElementById('img-debit') 
        var imgPix = document.getElementById('img-pix')

        function hoverImgColor(img) {
            if (img == 'white_credit') imgCredit.src="{% static 'imagens/cartão_white.png' %}"
            if (img == 'white_debit') imgDebit.src="{% static 'imagens/cartão_white.png' %}"
            if (img == 'white_pix') imgPix.src="{% static 'imagens/pix_white.png' %}"
        }


        function backImgColor(btn, img) {
            if (btn.classList.contains('btn-active')) return
            if (img == 'blue_credit') imgCredit.src="{% static 'imagens/cartão.png' %}"
            if (img == 'blue_debit') imgDebit.src="{% static 'imagens/cartão.png' %}"
            if (img == 'blue_pix') imgPix.src="{% static 'imagens/pix.png' %}"
        }


        function changeImgColor(botao) {
            imgCredit.src="{% static 'imagens/cartão.png' %}"
            imgDebit.src="{% static 'imagens/cartão.png' %}"
            imgPix.src="{% static 'imagens/pix.png' %}"
            if (botao == btnCredito) imgCredit.src="{% static 'imagens/cartão_white.png' %}"
            if (botao == btnDebito) imgDebit.src="{% static 'imagens/cartão_white.png' %}"
            if (botao == btnPix) imgPix.src="{% static 'imagens/pix_white.png' %}"
        }

    </script>
{% endblock %}

cliente/templates/cliente/base_clientes.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Área Azul - Blumenau</title>
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'imagens/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'imagens/favicon-16x16.png' %}">
  <link rel="stylesheet" href="{% static 'css/cliente.css' %}">
</head>

<body>
    <div class="fullpage">

        <div class="sidebar">
            <div class="sidebar_upper">
                <div class="sb_upper_img">
                    <img src="{% static 'imagens/Logo-A-provisorio.png' %}" alt="Logo Área Azul" width="70%" class="logo-template" onclick="location.href='{% url 'index' %}'">
                </div>
                <div class="sb_upper_text">
                    <h3>Olá, <a href="{% url 'index' %}">{{user.client.name}}!</a></h3>
                </div>
                <h3 id="sb_upper_text_saldo">Saldo atual: R$ {{user.client.credits|floatformat:2}}</h3>
            </div>

            <div class="sidebar_lower">
                <div class="sidebar_options" onclick="location.href='{% url 'estacionar' user.client.id %}'">
                    <img src="{% static 'imagens/Estacionar.png' %}" alt="Icone Estacionar" width="25"><a href="{% url 'estacionar' user.client.id %}">Estacionar</a>
                </div>
                <div class="sidebar_options" onclick="location.href='{% url 'extrato' user.client.id %}'">
                    <img src="{% static 'imagens/Extrato.png' %}" alt="Icone Extrato" width="25"><a href="{% url 'extrato' user.client.id %}">Extrato</a>
                </div>
                <div class="sidebar_options" onclick="location.href='{% url 'creditos' user.client.id %}'">
                    <img src="{% static 'imagens/Adicionar_Creditos.png' %}" alt="Icone Adicionar_Creditos" width="25"><a href="{% url 'creditos' user.client.id %}">Adicionar Créditos</a>
                </div>
                <div class="sidebar_options" onclick="location.href='{% url 'veiculos' user.client.id %}'">
                    <img src="{% static 'imagens/Meus_Veiculos.png' %}" alt="Icone Meus_Veiculos" width="25"><a href="{% url 'veiculos' user.client.id %}">Meus Veículos</a>
                </div>
                <div class="sidebar_options" onclick="location.href='{% url 'dados' user.client.id %}'">
                    <img src="{% static 'imagens/Meus_Dados.svg' %}" alt="Icone Meus_Dados" width="25"><a href="{% url 'dados' user.client.id %}">Meus Dados</a>
                </div>
                <div class="sidebar_options" onclick="location.href='{% url 'logout' %}'">
                    <img src="{% static 'imagens/Sair.png' %}" alt="Icone Sair" width="25"><a href="{% url 'logout' %}">Sair</a>
                </div>
            </div>
        </div>
        
        <div class="page">
            <div class="page_title">
                <h3 id='page-title'>Titulo da Página</h3>
            </div>
            <div class="page_content">
                {% block content %}{% endblock %}   
            </div>
        </div>

    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/cliente.js' %}"></script>
</body>
</html>

cliente/templates/cliente/dados.html
{% extends 'cliente/base_clientes.html' %}
{% load static %}

{% block content %}
  <script>
      document.getElementById('page-title').innerHTML = 'Meus Dados'
  </script>

  <form action='' method='POST' class='dados-form' enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-box">
          <div class="perfil">
              <h2>Perfil:</h2>
              <span>CPF: {{user.username}}</span>
              <span>Nome: {{client.name}}</span>
              <span>E-mail: {{clientForm.email}}</span>
              <span>Telefone 01: {{clientForm.phone1}}</span>
              <span>Telefone 02: {{clientForm.phone2}}</span>
              <span id='import-img'>{{clientForm.profile_pic}}</span>
          </div>
          <div class="address">
              <h2>Endereço:</h2>
              <span>CEP: {{addressForm.zip_code}}</span>
              <span>Estado: {{addressForm.state}}</span>
              <span>Cidade: {{addressForm.city}}</span>
              <span>Bairro: {{addressForm.district}}</span>
              <span>Rua: {{addressForm.street_name}}</span>
              <span>Nº: {{addressForm.house_number}}</span>
              <span>Complemento: {{addressForm.complement}}</span>
          </div>
      </div>
      
      {% if messages %}
          {% for message in messages %}
          
              <div class="cliente_messages {{message.tags}}">
                  <p>{{message}}</p><button type="button" class="btn-close" onclick="deletarMensagem(this)">&times;</button>
              </div>
    
          {% endfor %}
      {% endif %}

      <div class="button_confirm btn-dados"><button type="submit">Salvar</button></div>
  </form>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src='{% static "js/jquery.mask.js" %}'></script>

  <script>

      var form_fields = document.getElementsByTagName("input");

      for (var field in form_fields) {
      form_fields[field].className += "meus-dados-inputs";
      }

      $('#id_zip_code').mask('00000-000') 
      $('#id_phone1').mask('(00) 00000-0000')    
      $('#id_phone2').mask('(00) 00000-0000')  

  </script>

{% endblock %}

cliente/templates/cliente/excluir.html
{% extends 'cliente/base_clientes.html' %}
{% load static %}

{% block content %}
    <script>
        document.getElementById('page-title').innerHTML = 'Excluir Veículo'
    </script>

    <div class="div-excluir">
        <form class="form-excluir" action="{% url 'excluirVeiculo' user.client.id vehicle.id %}" method='POST'>
            <p>Você tem certeza que quer excluir o veículo <strong>"{{vehicle}}"</strong>?</p>
            <div class="botoes-excluir">
                {% csrf_token %}
                <a href="{% url 'veiculos' user.client.id %}">Cancelar</a>
                <button type="submit">Excluir</button>
            </div>
        </form>
    </div>

{% endblock %}

cliente/templates/cliente/extrato.html
{% extends 'cliente/base_clientes.html' %}
{% load static %}

{% block content %}
  <script>
    document.getElementById('page-title').innerHTML = 'Extrato'
  </script>
  
  <div class="date_filter_extrato">
    {% include 'partials/_date_filter.html' %}
  </div>
  <div class="div_table_extract">
    {% include 'partials/_table_extract.html' %}
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="{% static 'js/jquery.mask.js' %}"></script>
  <script src="{% static 'js/extrato.js' %}"></script>

{% endblock %}

cliente/templates/cliente/index.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/cliente.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:wght@600&display=swap" rel="stylesheet">
    <title>Área Azul - Blumenau</title>
</head>
<style>
    html {
        height: 100vh;
        width: 100%;
    }

    body {
        background-image: url('/static/imagens/Blumenau-Santa-Catarina-Black-White-90.png');
        background-size: cover;
    }
</style>
<body>
    <div class="cliente_main">
        <div class="div_logo"><img src="{% static 'imagens/Logo-A-provisorio.png' %}" alt="Logo Área Azul" width="300" class="logo"></div>
        <h2>Olá, {{user.client.name}}!</h2>
        {% if user.client.profile_pic %}<div class="div_profile-pic"><img src="{{request.user.client.profile_pic.url}}" alt="Imagem_Perfil" width=240 class='profile-pic'></div>{% endif %}
        <h1>Você tem</h1>
        <h1>R$ {{user.client.credits|floatformat:2}}</h1>
        <h1>em créditos.</h1>
    </div>

    <div class="cliente_options_div">
        <div class="cliente_options_links" onclick="location.href='{% url 'estacionar' user.client.id %}'">
            <img src="{% static 'imagens/Estacionar.png' %}" alt="Icone Estacionar" class="img-index"><a href="{% url 'estacionar' user.client.id %}">Estacionar</a>
        </div>
        <div class="cliente_options_links" onclick="location.href='{% url 'extrato' user.client.id %}'">
            <img src="{% static 'imagens/Extrato.png' %}" alt="Icone Extrato" class="img-index"><a href="{% url 'extrato' user.client.id %}">Extrato</a>
        </div>
        <div class="cliente_options_links" onclick="location.href='{% url 'creditos' user.client.id %}'">
            <img src="{% static 'imagens/Adicionar_Creditos.png' %}" alt="Icone Adicionar_Creditos" class="img-index"><a href="{% url 'creditos' user.client.id %}">Adicionar Créditos</a>
        </div>
        <div class="cliente_options_links" onclick="location.href='{% url 'veiculos' user.client.id %}'">
            <img src="{% static 'imagens/Meus_Veiculos.png' %}" alt="Icone Meus_Veiculos" class="img-index"><a href="{% url 'veiculos' user.client.id %}">Meus Veículos</a>
        </div>
        <div class="cliente_options_links" onclick="location.href='{% url 'dados' user.client.id %}'">
            <img src="{% static 'imagens/Meus_Dados.svg' %}" alt="Icone Meus_Dados" class="img-index"><a href="{% url 'dados' user.client.id %}">Meus Dados</a>
        </div>
        <div class="cliente_options_links" onclick="location.href='{% url 'logout' %}'">
            <img src="{% static 'imagens/Sair.png' %}" alt="Icone Sair" class="img-index"><a href="{% url 'logout' %}">Sair</a>
        </div>
    </div>
</body>
</html>